# Numpy Module

Learn about the python module numpy. Numpy is an extremely powerful module that provides high-speed multi-dimensional arrays. It is extremely useful for scientific computing and data science. It is highly recommenced that you learn the numpy module before moving into machine learning.

The numpy module implements support for powerful multi-dimensional arrays. It is mostly used for scientific computing but can be useful in other scenarios.

Installation
The numpy module does not come with a default python installation and must be installed. To do this please open up command prompt and type "pip install numpy".

### Using Numpy

Before we can start using numpy we must import it. Typically when we import numpy we import it as np.

In [3]:
import numpy as np

The simplest way to create a numpy array is to do so based on a list.



In [2]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)  # prints array([1,2,3,4])
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


To get the shape of the array we can use:

In [3]:
print(arr.shape)

(4,)


### Indexing

Indexing numpy arrays is slightly different lists in python. To index we use one set of square brackets with ints separated by commas.

In [30]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr[1,1])  # -> 5
print(arr.shape)

[[1 2 3]
 [4 5 6]]
5
(2, 3)


## Useful Methods

To get the amount of elements in the array we can use .size.

In [31]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.size)  # -> 6

6


To see the amount of dimensions in our array we can use .ndim.

In [32]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.ndim)  # -> 2

2


To add things into our arrays we can use np.append(array, item).



In [4]:
import numpy as np
arr = np.array([[[1,2,3],[1,2,3],[1,2,3]]])
print(arr)
print(arr.shape)
print(arr.ndim)
arr = np.append(arr, 7)
print(arr)  #-> array([1,2,3,7])

[[[1 2 3]
  [1 2 3]
  [1 2 3]]]
(1, 3, 3)
3
[1 2 3 1 2 3 1 2 3 7]


To delete something from our array we can use np.delete(array, index).



In [11]:
arr = np.array([1,2,3])
arr = np.delete(arr, 0)

print(arr)  #-> array([2,3])

[2 3]


## Array Creation


In the previous tutorial we learned how to create arrays based off of lists in python. In this tutorial you will learn how to use some of the numpy functions to create arrays in different ways.

To create an array filled completely with zeros we can use np.zeros(shape).

In [33]:
arr = np.zeros((2,3))

print(arr) 
print(type(arr))

[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


Similarity we can use np.ones(shape).

In [34]:
arr = np.ones((2,3))

print(arr) 
# Prints array([[1., 1., 1.],
#               [1., 1., 1.])

[[1. 1. 1.]
 [1. 1. 1.]]


Another useful function is np.arange().

In [5]:
arr = np.arange(10)
print(arr)                                         
# Prints array([0,1,2,3,4,5,6,7,8,9])

[0 1 2 3 4 5 6 7 8 9]


In [37]:
arr = np.arange(4, 10, 2)
print(arr)
# Prints array([4,6,8])

[4 6 8]


In [41]:
arr = np.arange(0,1,0.1)
print(arr)
print(type(arr))
# Prints array([0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
<class 'numpy.ndarray'>


We can also use .linspace(start, stop, values) in a similar way to .arange().

In [40]:
arr = np.linspace(1, 3, 6)
print(arr) # -> array([1. , 1.4, 1.8, 2.2, 2.6, 3. ])

# the linspace function will automatically calculate the step value
# based on the number of elements we specify

[1.  1.4 1.8 2.2 2.6 3. ]


We can also create an array full of a constant value using np.full(shape, value).



In [20]:
arr = np.full((2,2),8)
print(arr)  # -> array([[8, 8],
#                       [8, 8]])

[[8 8]
 [8 8]]


To create an identity matrix we can use np.eye(size).



In [23]:
arr = np.eye(4)
print(arr) # -> array([[1., 0., 0.],
#                      [0., 1., 0.],
#                      [0., 0., 1.]])

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


To create a random array of floats we can use np.random.random(size).



In [24]:
arr = np.random.random((2,2))
print(arr) # ->array([[0.65208707,0.02997459],
#                     [0.05827481, 0.34312981]])

[[0.37879871 0.82762169]
 [0.67004589 0.54628479]]


## Dtype

When creating arrays we sometimes have the option to specify their data type using the argument dtype=, like so:

In [7]:
arr = np.ones((3,3), dtype=str)
print(arr)

[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]


In [10]:
arr = np.zeros((2,2), dtype=int)
print(arr)

[[0 0]
 [0 0]]


## Array Math

Another reason that numpy is so useful is because of its extensive implementation for array operations and math. Numpy has tons of functions that save us tons of time and can perform operations very quickly

The following operations are supported on numpy arrays. They perform whats known as element-wise operations.
- addition: + or np.add()
- subtraction: - or np.subtract()
- multiplication: * or np.multiply()
- division: / or np.divide()
- square root: np.sqrt()

In [43]:
import numpy as np
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x + y)  # -> array([[ 6,  8],
#                  [10, 12]])

print(x - y)  # -> array([[-4, -4],
#                  [-4, -4]])

print(x * y)  # -> array([[ 5, 12],
#                  [21, 32]])

print(x / y)  # -> array([[0.2       , 0.33333333],
#                  [0.42857143, 0.5       ]])

print(np.sqrt(x))  # -> array([[1.        , 1.41421356],
#                       [1.73205081, 2.        ]])

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


To take the dot product of two arrays we can use .dot().

In [6]:
import numpy as np
v = np.array([[1,1],[2,2]])
w = np.array([[1,1],[2,2]])

print(v.dot(w)) # -> 229
print(w.dot(v)) # -> 229

print(np.dot(v, w)) # -> 229

[[3 3]
 [6 6]]
[[3 3]
 [6 6]]
[[3 3]
 [6 6]]


When we take the dot product of two arrays of the same size we get a scalar. Otherwise we get what's called an inner product.

To transpose a matrix or array we can use .T.

In [53]:
import numpy as np
v = np.array([[9,10], [98, 67]])

v.T  # ->  array([[ 9, 98],
#                 [10, 67]])

array([[ 9, 98],
       [10, 67]])

To take the sum of an array we can use np.sum(axis=).

In [48]:
import numpy as np
v = np.array([[9,10], [98, 67]])
print(v)
print(np.sum(v))  # -> 184
np.sum(v, axis=0)  # array([107,  77]), this gives us the sum of the columns stored in an array

[[ 9 10]
 [98 67]]
184


array([107,  77])

In [10]:
import re
text="A random string."
pattern=re.compile("A rae")
result=pattern.search(text)
print(result)

<_sre.SRE_Match object; span=(0, 3), match='A r'>


In [13]:
import re
text="A random string."
pattern1=re.compile("[ABC]")
result1=pattern1.search(text)
print(result1)

<_sre.SRE_Match object; span=(0, 1), match='B'>


In [15]:
import re
text="A random string."
pattern2=re.compile("[ran]+")
result2=pattern2.search(text)
print(result2)

<_sre.SRE_Match object; span=(2, 5), match='ran'>
